services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app   
    command: sh -c "yarn install && yarn start:dev"
    depends_on:
      - postgres
    env_file: .env
  postgres:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgweb:
    image: sosedoff/pgweb
    ports: 
    - "8081:8081" 
    environment:
    - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres-data:
